services:
  - type: web
    name: jizhang-system
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgresql://postgres:jizhanggulixitogn@db.ezypdynyvilospzelsci.supabase.co:5432/postgres
      - key: DB_ADAPTER
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
